### ISSUE TITLE
Log file present in the gem release

### ISSUE THREAD

**Issue by mensfeld** [alexdowad/bit-twiddle#3]
I may be wrong, but is this file needed? https://my.diffend.io/gems/bit-twiddle/0.0.7/0.1.0#d2h-528066 :thinking:

**Comment by alexdowad** [comment]
(Gulp)

Wow. How did I manage that?

**Comment by alexdowad** [comment]
Just working on pushing out a fixed gem.

**Comment by mensfeld** [comment]
I don't know how you did this but I will make sure to ping you each time you do this ;) https://diffend.io monitors quality of gems released and I', doing my best to report things when I find them

**Comment by alexdowad** [comment]
@mensfeld I pushed a new version. Credited you in the commit log.

Have a look at this:

https://github.com/alexdowad/bit-twiddle/commit/91c1098a816949a8f72b17118aa3ed8dcafc976b

**Comment by alexdowad** [comment]
@mensfeld You motivated me to look at my other gems and see what files I am actually bundling in the gem.

I can see that in another one, I included all the spec tests. What do you think? Is that just junk which shouldn't be included?

**Comment by mensfeld** [comment]
>  I included all the spec tests. What do you think? Is that just junk that shouldn't be included?

By all means I would not cal specs junk :) It may or may not be obsolete in the releases. If your gems are not part of Linux distro releases, thus do not run test suits during Linux builds, etc I would advise against including them in the gem releases.
